# Generated by Django 4.2.16 on 2024-11-26 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('examples', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NonAlcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('examples', models.TextField()),
                ('beverages', models.ManyToManyField(related_name='nonalcohols', to='movies.beverage')),
            ],
        ),
        migrations.CreateModel(
            name='Whiskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('examples', models.TextField()),
                ('beverages', models.ManyToManyField(related_name='whiskies', to='movies.beverage')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('examples', models.TextField()),
                ('beverages', models.ManyToManyField(related_name='wines', to='movies.beverage')),
            ],
        ),
        migrations.CreateModel(
            name='WineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wine_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movies.wine')),
            ],
        ),
        migrations.CreateModel(
            name='WhiskeyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='whiskey_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('whiskey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movies.whiskey')),
            ],
        ),
        migrations.CreateModel(
            name='NonAlcoholImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='nonalcohol_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('nonalcohol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movies.nonalcohol')),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtype', models.CharField(max_length=50)),
                ('beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.beverage')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
                ('adult', models.BooleanField()),
                ('star_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.moviegenre')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='beer_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movies.beer')),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='beverages',
            field=models.ManyToManyField(related_name='beers', to='movies.beverage'),
        ),
    ]
